# Generated by Django 6.1.1 on 2026-10-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('opis_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('rack_id', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=5, max_digits=8)),
                ('price_samples', models.PositiveSmallIntegerField(default=1)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('geocode_source', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['opis_id'],
            },
        ),
    ]
